"""add client contact

Revision ID: 05a5fe893444
Revises: fbd51399f01d
Create Date: 2026-01-12 11:05:23.572489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05a5fe893444'
down_revision: Union[str, Sequence[str], None] = 'fbd51399f01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure the PostgreSQL ENUM type exists and avoid duplicate creation
    shipmentstatus_enum = postgresql.ENUM(
        'placed', 'processing', 'shipped', 'in_transit', 'out_for_delivery', 'delivered',
        name='shipmentstatus',
        create_type=False
    )
    # Create the enum if missing
    shipmentstatus_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('shipment_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('status', shipmentstatus_enum, nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shipmentevent')
    # Backfill existing NULLs to satisfy NOT NULL constraints
    op.execute("UPDATE seller SET address = 'Unknown' WHERE address IS NULL")
    op.execute("UPDATE seller SET zip_code = 0 WHERE zip_code IS NULL")

    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('shipment', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shipment', sa.Column('client_contact_phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'client_contact_phone')
    op.drop_column('shipment', 'client_contact_email')
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('shipmentevent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('shipment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], name=op.f('shipmentevent_shipment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shipmentevent_pkey'))
    )
    op.drop_table('shipment_event')
    # ### end Alembic commands ###
